### ISSUE TITLE
ski_areas.geojson location information is missing

### ISSUE THREAD

**Issue by dhimmel** [russellporter/openskimap.org#135]
I downloaded `https://tiles.skimap.org/geojson/ski_areas.geojson` on 2024-08-17 and noticed the location fields have a new schema, which is [nicely defined](https://github.com/russellporter/openskidata-format/blob/67bbb7c1ee5b5e25d7252a7284a1ea0f5c097f80/src/Location.ts) in `openskidata-format`. So now all location information will be nested under the `location` field.

However, it appears that all ski areas have a null value for `location` rather than actual information. So perhaps the code to generate `ski_areas.geojson` must be updated for the new schema?

**Comment by russellporter** [comment]
should be resolved now

**Comment by dhimmel** [comment]
Confirming that a fresh download of `ski_areas.geojson` contains location! Thanks
