### ISSUE TITLE
Increase transparency of ski run colors for better map readability

### ISSUE THREAD

**Issue by appdevsw** [russellporter/openskimap.org#142]
Hi OpenSkiMap team,

I have a suggestion regarding the transparency of ski run colors on the map. Currently, wide ski runs are displayed as large colored areas (in red, blue, etc.), but the opacity level makes it difficult to see underlying map details like contour lines and terrain features.

Would it be possible to increase the transparency of the ski run colors? This would allow the underlying map elements to be more visible and improve readability for users.

Thank you for considering this enhancement, and thanks for your hard work on OpenSkiMap!

Best regards

**Comment by russellporter** [comment]
Hi there, thanks for the suggestion. I've reduced the opacity significantly so it should be easier to see through the runs:
<img width="513" alt="Screenshot 2024-11-06 at 10 32 45 PM" src="https://github.com/user-attachments/assets/13c726c3-e562-4920-b781-fe9d9111c441">

**Comment by appdevsw** [comment]
@russellporter  Thank you very much! Your modification is great!
