### ISSUE TITLE
Show cogwheel trains on the map when they are associated with a ski area

### ISSUE THREAD

**Issue by russellporter** [russellporter/openskimap.org#17]
It's probably a bit difficult to accurately determine which trains are used for skiing, but a starting point would be to add cogwheel trains (in addition to previously added funiculars).

For both cogwheel/funiculars, we could add a postprocessing step in the processor to remove them from the map if they are not associated with a ski run in the feature graph.

**Comment by tjorim** [comment]
Was this already implemented? Just wondering if the 'issue' is with the OSM data or openskimap. There is a train in Zermatt/Matterhorn that's included in a ski pass and necessary for some runs.

**Comment by russellporter** [comment]
As most railways are not part of a ski resort, in order for a railway to appear on the map, it needs to be added to a `site=piste` relation in OSM. That relation should ideally include all lifts / runs in the resort. It looks like Zermatt doesn't have a site=piste relation currently.
