### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by leonmvd** [russellporter/openskimap.org#97]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/9214202/210975767-7f04676f-fc1b-497d-801f-09ccd40f69aa.png">

**Comment by russellporter** [comment]
Thanks, I had a couple other reports of issues today. I just did a quick fix. Can you check if it is working for you now?

**Comment by leonmvd** [comment]
Working fine again. Thanks!

Op vrijdag 6 januari 2023 schreef Russell Porter ***@***.***>:
